-- 
-- Regular Tables
--

CREATE TABLE Customer (
    customer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    street_address VARCHAR(130),
    city VARCHAR(130),
    state CHAR(2),
    zip_code NUMBER,
    phone_number NUMBER,
    date_first_rented DATE,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);
						
CREATE TABLE Distributors (
    distributor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    distributor_name VARCHAR(130),
    contact_name VARCHAR(130),
    address VARCHAR(130),
    phone_number NUMBER,
    CONSTRAINT pk_distributors PRIMARY KEY (distributor_id)
);
						
CREATE TABLE Actors_Actresses (
    actor_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(130),
    birth_date DATE,
    CONSTRAINT pk_actors PRIMARY KEY (actor_id)
);

CREATE TABLE Directors (
    director_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(130),
    birth_date DATE,
    CONSTRAINT pk_directors PRIMARY KEY (director_id)
);

CREATE TABLE Award_Types (
    award_type_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    award_name VARCHAR(130),
    CONSTRAINT pk_award_types PRIMARY KEY (award_type_id)
);

CREATE TABLE Movie_Titles (
    movie_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    movie_title VARCHAR(255),
    year_released DATE,
    length_of_film NUMBER,
    genre VARCHAR(130),
    rating VARCHAR(10),
    CONSTRAINT pk_movies PRIMARY KEY (movie_id)
);
			
--
-- Related Tables
--

CREATE TABLE Orders (
    order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    purchase_date DATE,
    shipping_cost FLOAT,
    distributor_id NUMBER,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT fk_order_distributor FOREIGN KEY (distributor_id) REFERENCES Distributors(distributor_id)
);

CREATE TABLE VHS_DVD (
    video_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    format VARCHAR(10),
    cost_standard_rate FLOAT,
    order_id NUMBER,
    movie_id NUMBER,
    CONSTRAINT pk_videos PRIMARY KEY (video_id),
    CONSTRAINT fk_video_order FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    CONSTRAINT fk_video_movie FOREIGN KEY (movie_id) REFERENCES Movie_Titles(movie_id)
);

CREATE TABLE Distributor_Catalog (
    catalog_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    wholesale_price FLOAT,
    format VARCHAR(10),
    distributor_id NUMBER,
    movie_id NUMBER,
    CONSTRAINT pk_catalog PRIMARY KEY (catalog_id),
    CONSTRAINT fk_catalog_distributor FOREIGN KEY (distributor_id) REFERENCES Distributors(distributor_id),
    CONSTRAINT fk_catalog_movie FOREIGN KEY (movie_id) REFERENCES Movie_Titles(movie_id)
);

CREATE TABLE Rentals (
    rental_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    date_returned DATE,
    date_issued DATE,
    cost_standard_rate FLOAT,
    fees_late_return FLOAT,
    fees_damaged FLOAT,
    fees_no_rewind FLOAT,
    cost_taxes FLOAT,
    cost_discount FLOAT,
    cost_total FLOAT,
    video_id NUMBER,
    customer_id NUMBER,
    CONSTRAINT pk_rentals PRIMARY KEY (rental_id),
    CONSTRAINT fk_rental_video FOREIGN KEY (video_id) REFERENCES VHS_DVD(video_id),
    CONSTRAINT fk_rental_customer FOREIGN KEY (customer_id) REFERENCES Customer(customer_id)
);

--
-- Reference Tables
--

CREATE TABLE Order_Items (
    quantity NUMBER,
    price_per_item FLOAT,
    order_id NUMBER,
    catalog_id NUMBER,
    CONSTRAINT fk_orderitem_order FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    CONSTRAINT fk_orderitem_catalog FOREIGN KEY (catalog_id) REFERENCES Distributor_Catalog(catalog_id)
);

CREATE TABLE Awards (
    actor_id NUMBER,
    movie_id NUMBER,
    director_id NUMBER,
    award_type_id NUMBER,
    CONSTRAINT fk_awards_movie FOREIGN KEY (movie_id) REFERENCES Movie_Titles(movie_id),
    CONSTRAINT fk_awards_actor FOREIGN KEY (actor_id) REFERENCES Actors_Actresses(actor_id),
    CONSTRAINT fk_awards_director FOREIGN KEY (director_id) REFERENCES Directors(director_id),
    CONSTRAINT fk_awards_type FOREIGN KEY (award_type_id) REFERENCES Award_Types(award_type_id)
);

CREATE TABLE Serial_Numbers (
    serial_number VARCHAR(255),
    video_id NUMBER,
    distributor_id NUMBER,
    CONSTRAINT fk_serial_video FOREIGN KEY (video_id) REFERENCES VHS_DVD(video_id),
    CONSTRAINT fk_serial_distributor FOREIGN KEY (distributor_id) REFERENCES Distributors(distributor_id)
);

CREATE TABLE Associated_People (
    actor_id NUMBER,
    movie_id NUMBER,
    director_id NUMBER,
    CONSTRAINT fk_associated_movie FOREIGN KEY (movie_id) REFERENCES Movie_Titles(movie_id),
    CONSTRAINT fk_associated_actor FOREIGN KEY (actor_id) REFERENCES Actors_Actresses(actor_id),
    CONSTRAINT fk_associated_director FOREIGN KEY (director_id) REFERENCES Directors(director_id)
);